### PR TITLE
feat: added StatusBadge for programs and processes + added locales en/fr + fixed locales toggle button

### LINKED ISSUE #10: Extend Badge component and use it where it has to be used
The Badge component should support more colours and we should use it for instance on the Program page.

### PR DESCRIPTION
**Pull request by plcharriere**

### CODE REVIEW

File: src/components/Sidebar.vue [hunk 1]
```diff
@@ -19,12 +19,7 @@
         </div>
       </div>
       <div class="flex mb-5 text-2xl justify-evenly">
-        <a class="mx-2 icon-btn" :title="t('button.toggle_dark')" @click="isDark = !isDark">
-          <carbon-moon v-if="isDark" />
-          <carbon-sun v-else />
-        </a>
-
-        <a class="mx-2 icon-btn" :title="t('button.toggle_langs')" @click="toggleLocales">
+        <a class="mx-2 icon-btn" :title="t('buttons.toggle_lang')" @click="toggleLocales">
```
Comment (Devessier) [inline src/components/Sidebar.vue]: I don’t know why @antfu used a link. This should be a button, it does not redirect to a page, does it ?

File: src/components/Sidebar.vue [hunk 2]
```diff
@@ -36,43 +31,74 @@
...
 
-import { useI18n } from 'vue-i18n'
-import { isDark } from '/~/logics'
+export default defineComponent({
+  setup() {
+    const { t, availableLocales, locale } = useI18n()
 
-const { t, availableLocales, locale } = useI18n()
+    const toggleLocales = () => {
+      const locales = availableLocales
```
Comment (Devessier) [inline src/components/Sidebar.vue]: I think we can just assign a new value to the global i18n instance.

File: src/components/Sidebar.vue [hunk 3]
```diff
@@ -36,43 +31,74 @@
...
+      locale.value = locales[(locales.indexOf(locale.value) + 1) % locales.length]
```
Comment (Devessier) [inline src/components/Sidebar.vue]: We may probably want to use a more straightforward method to change the locale. A ternary could be enough, but taking the next item in an array seems to me a bit “magic”.

File: src/components/StatusBadge.vue [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+import { ProgramState } from '/~/types/index'
+import { useI18n } from 'vue-i18n'
+
+export default defineComponent({
+  props: {
+    light: {
+      type: Boolean,
+      default: false,
+    },
+    status: {
```
Comment (Devessier) [inline src/components/StatusBadge.vue:21]: If the status can only take some known values, we could add a TypeScript annotation as well as a runtime validator.

File: src/components/programs/Program.vue [hunk 5]
```diff
@@ -1,68 +1,56 @@
...
+  <router-link class="flex rounded-lg p-10 bg-white border border-solid shadow-sm cursor-pointer hover:bg-gray-50" :to="programUrl">
     <div class="flex items-center w-full">
       <div class="flex items-center justify-between w-full">
         <div class="flex flex-col">
           <div class="text-xl">
             {{ id }}
           </div>
           <div class="text-gray-500">
-            3/3 processes
+            {{ runningProcesses }}/{{ processes.length }} process{{ processes.length > 1 ? "es" : "" }}
```
Comment (Devessier) [inline src/components/programs/Program.vue]: We can handle plural forms directly using Vue I18n: https://vue-i18n-next.intlify.dev/guide/essentials/pluralization.html#basic-usage.

File: src/pages/programs/[id].vue [hunk 6]
```diff
@@ -10,7 +10,10 @@
 
     <AppLayout v-else>
       <template #title>
-        {{ program.id }}
+        <router-link to="/programs" :title="t('buttons.back')">
```
Comment (Devessier) [inline src/pages/programs/[id].vue:13]: This back button is really nice!
We could even use it in the Layout component!

**Review by Devessier — CHANGES_REQUESTED** [review]
Very good work!
I love the back button in the Program page!
We could make some minor improvements to have a stronger code.

**Review by Devessier — APPROVED** [review]
Perfect! We can merge.
